Nexters/boolti-web

- apps/admin/vite.config.ts
- apps/preview/vite.config.ts
- apps/super-admin/vite.config.ts
- packages/api/package.json
@Puterism 빌드가 안되어서 넷리파이 테스트를 못해보고 있어서 선 머지 할게!
> fix: 빌드 오류 수정

- apps/admin/src/App.tsx
- apps/admin/src/components/Header/Header.styles.ts
- apps/admin/src/components/Header/Header.tsx
- apps/admin/src/components/Layout/Layout.styles.ts
- apps/admin/src/components/Layout/Layout.tsx
- apps/admin/src/pages/HomePage/HomePage.styles.ts
- apps/admin/src/pages/HomePage/HomePage.tsx
- apps/admin/src/styles/ThemeProvider.tsx
- apps/admin/src/styles/breakpoint.ts
- apps/admin/src/styles/emotion.d.ts
- Layout 컴포넌트 구현
- 사용 예시는 HomePage.tsx를 확인해주세요.
- <img width="1588" alt="스크린샷 2024-01-27 오후 4 06 33" src="https://github.com/Nexters/boolti-web/assets/2542730/4822e52a-5c35-4d92-9691-c7b5223613f7">
> feat: Layout 컴포넌트 구현

- apps/preview/src/App.tsx
- packages/ui/src/components/Button/Button.style.ts
- packages/ui/src/components/TextButton/TextButton.style.ts
- packages/ui/src/components/TextButton/index.tsx
- packages/ui/src/components/index.ts
- TextButton 컴포넌트 추가
- disabled 상태일때 hover, active 인터랙션 제거
> feat: TextButton 컴포넌트 추가

- apps/preview/src/App.tsx
- packages/ui/src/components/Button/Button.styles.ts
- packages/ui/src/components/Button/index.tsx
- packages/ui/src/components/DatePicker/DatePicker.styles.ts
- packages/ui/src/components/DatePicker/index.tsx
- packages/ui/src/components/TextButton/index.tsx
- packages/ui/src/components/TextField/TextField.styles.ts
- packages/ui/src/components/TextField/index.tsx
- packages/ui/src/components/index.ts
> feat: TextField, DatePicker 컴포넌트 추가

- apps/storybook/stories/TextField.stories.tsx
- packages/ui/src/components/TextField/TextField.styles.ts
- packages/ui/src/components/TextField/index.tsx
> feat: TextField 에러 있는 케이스 추가

- .github/CODEOWNERS
리뷰지정할 때 검색안하고 상단에 나오도록 하기위해 추가
> chore: CODEOWNER 추가

- .pnp.cjs
- apps/admin/package.json
- apps/admin/src/App.tsx
- apps/admin/src/components/ShowList/index.tsx
- apps/admin/src/components/TicketForm/GeneralTicketForm.tsx
- apps/admin/src/components/TicketForm/InvitationTicketForm.tsx
- apps/admin/src/components/TicketForm/TicketForm.styles.ts
- apps/admin/src/constants/routes.ts
- apps/admin/src/pages/ShowAddPage/ShowAddPage.styles.ts
- apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
- packages/icon/src/components/FileUp.tsx
- packages/icon/src/components/index.ts
- packages/ui/src/components/TextField/TextField.styles.ts
- packages/ui/src/components/TextField/index.tsx
- packages/ui/src/systems/palette.ts
- yarn.lock
> feat: 공연 등록하기 UI 구현

- .pnp.cjs
- apps/admin/package.json
- apps/admin/src/App.tsx
- apps/admin/src/components/Layout/Layout.styles.ts
- apps/admin/src/components/Layout/index.tsx
- apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/constants/routes.ts
- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
- yarn.lock
공연 상세 페이지에서 공통적으로 사용되는 헤더 컴포넌트를 구현합니다.
> feat: ShowDetailHeader 컴포넌트 구현

- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowBasicInfoFormContent.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowInfoFormContent.styles.ts
- apps/admin/src/components/ShowInfoFormContent/ShowInvitationCodeList.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowTicketInfoFormContent.tsx
- apps/admin/src/components/TicketForm/InvitationTicketForm.tsx
- apps/admin/src/components/TicketForm/SalesTicketForm.tsx
- apps/admin/src/pages/ShowAddPage/ShowAddPage.tsx
- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
- apps/admin/src/pages/ShowTicketPage/ShowTicketPage.styles.ts
- apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
- packages/api/src/mutations/index.ts
- packages/api/src/mutations/useCreateInvitationTicket.ts
- packages/api/src/mutations/useCreateSalesTicket.ts
- packages/api/src/mutations/useDeleteInvitationTicket.ts
- packages/api/src/mutations/useDeleteSalesTicket.ts
- packages/api/src/mutations/useEditSalesTicketInfo.tsx
- packages/api/src/queries/index.ts
- packages/api/src/queries/useInvitationCodeList.ts
- packages/api/src/queries/useInvitationTicketList.ts
- packages/api/src/queries/useSalesTicketList.ts
- packages/api/src/queryKey.ts
- packages/api/src/types/show.ts
- packages/icon/src/components/ChevronDown.tsx
- packages/icon/src/components/ChevronUp.tsx
- packages/icon/src/components/index.ts
- 티켓 관리 페이지 UI를 구성합니다.
- 관련 API를 연동합니다.
> feat: 티켓 관리 페이지 UI 구성 및 API 연동

- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
> feat: 공연 티켓 판매 중에도 공연 정보를 수정할 수 있도록 수정

- .pnp.cjs
- apps/admin/index.html
- apps/admin/package.json
- apps/admin/src/pages/Login/LoginPage.tsx
- apps/admin/vite.config.ts
- packages/api/src/mutations/index.ts
- packages/api/src/mutations/useAppleLogin.ts
- packages/api/src/mutations/useKakaoToken.ts
- yarn.lock
- 애플 로그인을 구현합니다.
- 애플 로그인 구현을 위해 개발 서버 host를 https://dev.boolti.in:8080 으로 변경하였습니다. 다음의 순서대로 개발 서버 세팅을 변경해주세요.
1. `/etc/hosts`에`127.0.0.1 dev.boolti.in` 추가
2. HTTPS 인증서 발급을 위한 mkcert 설치
```
brew install mkcert
brew install nss # if you use Firefox
mkcert -install
```
3. apps/admin 으로 이동 후, 인증서를 발급
```
cd apps/admin
mkcert dev.boolti.in
```
4. 개발 서버 실행 시, `https://dev.boolti.in:8080`으로 잘 접속되는지 확인
> feat: 애플 로그인 구현 및 개발 서버 host 변경

- apps/admin/src/components/Header/Header.styles.ts
- apps/admin/src/components/Layout/Layout.styles.ts
- apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowInfoFormContent.styles.ts
- apps/admin/src/components/ShowInfoFormContent/ShowInvitationCodeList.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
- apps/admin/src/components/ShowInfoFormContent/ShowSalesTicketFormContent.tsx
- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.styles.ts
- apps/admin/src/pages/ShowInfoPage/ShowInfoPage.tsx
- apps/admin/src/pages/ShowTicketPage/ShowTicketPage.styles.ts
- apps/admin/src/pages/ShowTicketPage/ShowTicketPage.tsx
- packages/ui/src/components/Confirm/Confirm.styles.ts
- 공연 기본 정보 및 티켓 관리 페이지 모바일 대응
- 티켓 판매가 종료된 공연에서 미사용 초청 코드에 사용 가능 뱃지가 표시되는 문제 수정
- 공연이 종료되었을 때, 공연 삭제를 할 수 없는 문제 수정
> feat: 공연 기본 정보 및 티켓 관리 페이지 모바일 대응 / QA 버그 수정

- apps/admin/src/components/ShowInfoFormContent/ShowInvitationTicketFormContent.tsx
- 초청 티켓이 하나만 있을 경우 삭제할 수 없었던 문제 수정
> fix: 초청 티켓이 하나만 있을 경우 삭제할 수 없었던 문제 수정

- .pnp.cjs
- apps/admin/src/components/SettlementDialogContent/index.tsx
- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/pages/ShowSettlementPage/ShowSettlementPage.styles.ts
- apps/admin/src/pages/ShowSettlementPage/ShowSettlementPage.tsx
- apps/super-admin/src/pages/HomePage/index.tsx
- apps/super-admin/src/pages/SettlementPage/index.tsx
- package.json
- packages/api/src/mutations/index.ts
- packages/api/src/mutations/useDeleteBankAccountCopyPhoto.ts
- packages/api/src/mutations/useDeleteIDCardPhotoFile.ts
- packages/api/src/queries/index.ts
- packages/api/src/queries/useSettlementBanners.ts
- packages/api/src/queries/useShowSettlementStatement.ts
- packages/api/src/queryKey.ts
- packages/api/src/types/show.ts
- packages/config-eslint/package.json
- turbo.json
- yarn.lock
- [정산 관리 - 정산 계좌 추가 완료 후 팝업 안 닫히는 문제 수정](https://github.com/Nexters/boolti-web/commit/101a2b74070799a5d43ee3db311f2f4188e7ca14)
- [정산 관리 - 은행 계좌를 중복 등록할 수 없도록 수정](https://github.com/Nexters/boolti-web/commit/dc24929369b8746c8cc702454c13c8d74b58e98e)
- [정산 관리 - 파일 업로드 이후 파일을 다운로드할 수 있도록 수정](https://github.com/Nexters/boolti-web/commit/59b3bd1a4fb9b1f561aaac8c2b6102e5c96717f5)
- [정산 관리 - 정산 정보를 모두 입력했을 때 정산 정보를 입력해 주세요 메시지가 보이지 않도록 수정](https://github.com/Nexters/boolti-web/commit/8d37a14e9d71a27836929950aade8e935a8f52a6)
- [슈퍼 어드민 공연 목록에서 판매자 -> 주최자로 라벨명 변경](https://github.com/Nexters/boolti-web/commit/0ee4a7c139868b5fda50f7e58b0a2d5767d9e7cc)
- [슈퍼 어드민 정산 계좌 정보에 예금주가 포함되도록 수정](https://github.com/Nexters/boolti-web/commit/380e7818ed8245c684369dfbf11707e85167ab9b)
- [내역서 생성하기 활성화 조건 …
> 정산 플로우 QA 반영

- apps/admin/src/pages/ShowSettlementPage/ShowSettlementPage.styles.ts
- apps/admin/src/pages/ShowSettlementPage/ShowSettlementPage.tsx
> feat: 정산 관리 페이지에서 정산 계좌 입력 삭제

- apps/admin/src/components/AuthoritySettingDialogContent/components/HostInputForm/HostInputForm.styles.ts
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostInputForm/index.tsx
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostList/HostList.styles.ts
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostList/index.tsx
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostListItem/HostListItem.styles.ts
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostListItem/index.tsx
- apps/admin/src/components/AuthoritySettingDialogContent/index.tsx
- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/components/ShowList/index.tsx
- apps/admin/src/components/ShowListItem/index.tsx
- apps/admin/src/pages/GiftRegisterPage/components/GiftGuide/index.tsx
- apps/admin/src/pages/ShowReservationPage/ShowReservationPage.styles.ts
- apps/admin/src/pages/ShowReservationPage/index.tsx
- packages/api/src/mutations/useDeleteHost.ts
- packages/api/src/types/error.ts
- packages/api/src/types/show.ts
- packages/icon/src/components/ChevronDown.tsx
- packages/ui/src/components/Alert/Alert.styles.ts
- packages/ui/src/components/Confirm/Confirm.styles.ts
- packages/ui/src/components/Dialog/Dialog.styles.ts
- 본인 권한 변경 혹은 삭제 시 flow 개선 ( dialog close, redriect )
- 권한 설정 Dialog 스타일 수정
- 방문자 관리 탭 empty 화면 수정
- 중복 초대 시 에러 처리
> Fix: 권한 설정 디자인 QA

- apps/admin/src/components/AuthoritySettingDialogContent/components/HostInputForm/HostInputForm.styles.ts
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostInputForm/index.tsx
- apps/admin/src/components/AuthoritySettingDialogContent/components/HostListItem/HostListItem.styles.ts
- apps/admin/src/components/ShowDetailLayout/ShowDetailLayout.styles.ts
- apps/admin/src/pages/ShowEnterancePage/ShowEnterancePage.styles.ts
- apps/admin/src/pages/ShowEnterancePage/index.tsx
- packages/ui/src/components/Dialog/Dialog.styles.ts
- 호스트 Input Form 해쉬태그 상시 노출
- 모바일 공연 상세 헤더의 공연 제목이 길 때 줄임표시 적용
> Fix: 디자인 QA

- apps/admin/src/components/ProfileDropdown/ProfileDropdown.styles.ts
- apps/admin/src/components/ShowDetailLayout/index.tsx
- apps/admin/src/pages/Landing/components/Header/Header.styles.ts
- apps/admin/src/pages/QRPage/QRPage.tsx
- apps/admin/src/pages/ShowEnterancePage/index.tsx
- packages/icon/src/components/ChevronUp.tsx
1. QR 페이지 헤더컬러 #FFF로 변경
2. 랜딩 페이지 프로필 드롭다운 상하 화살표 컬러 #FFF로 변경
3. 공연 상세 로그아웃 버튼 프로필 드롭다운 컴포넌트로 대체
4. 입장 관리 페이지 오타 수정
> Fix: 자잘한 디자인 QA

- apps/admin/src/App.tsx
- apps/admin/src/atoms/useAuthAtom.ts
- apps/admin/src/components/AccountDeleteForm/index.tsx
- apps/admin/src/components/ErrorBoundary/GlobalErrorBoundary.tsx
- apps/admin/src/components/ProfileDropdown/ProfileDropdown.styles.ts
- apps/admin/src/components/ProfileDropdown/index.tsx
- apps/admin/src/pages/HomePage/HomePage.tsx
- apps/admin/src/pages/Landing/components/Header/Header.styles.ts
- apps/admin/src/pages/Landing/components/Header/index.tsx
- packages/api/src/QueryClientProvider.tsx
- packages/api/src/fetcher.ts
- packages/api/src/mutations/useKakaoToken.ts
- packages/api/src/mutations/useLogout.ts
- packages/api/src/queries/useUserSummary.ts
* fix: 드롭다운 색상 수정
* fix: 인증 관련 오류 수정
* fix: 글로벌 에러바운더리 추가
* chore: 주석 코드 리버트
> fix: 401 에러 관련 수정 (#140)

- apps/preview/src/pages/ShowPreviewPage/ShowPreviewPage.styles.ts
- apps/preview/src/pages/ShowPreviewPage/ShowPreviewPage.tsx
- packages/ui/src/components/ShowPreview/ShowPreview.styles.ts
- packages/ui/src/components/ShowPreview/index.tsx
- 포스터 사이즈 변경
- 불티 로고 클릭 시 랜딩 페이지 이동
- 미리보기 페이지 영역 padding 수정
> feat: 미리보기 디자인 QA 반영

- apps/preview/src/pages/ShowPreviewPage/ShowPreviewPage.styles.ts
- apps/preview/src/pages/ShowPreviewPage/ShowPreviewPage.tsx
- packages/ui/src/components/ShowPreview/ShowPreview.styles.ts
- packages/ui/src/components/ShowPreview/index.tsx
- 포스터 사이즈 변경
- 불티 로고 클릭 시 랜딩 페이지 이동
- 미리보기 페이지 영역 padding 수정
> feat: 미리보기 디자인 QA 운영 반영

- apps/admin/src/components/ProfileDropdown/ProfileDropdown.styles.ts
- apps/admin/src/components/SettingDialogContent/SettingDialogContent.styles.ts
- apps/admin/src/components/SettingDialogContent/index.tsx
- apps/admin/src/components/UserProfile/UserProfile.styles.ts
- apps/admin/src/pages/HomePage/HomePage.tsx
- apps/admin/src/pages/Landing/components/Header/index.tsx
- apps/admin/src/pages/QRPage/QRPage.tsx
- apps/admin/src/pages/SignUpComplete/SignUpCompletePage.tsx
- apps/super-admin/src/components/PaymentTable/PaymentTable.tsx
- apps/super-admin/src/pages/EntrancePage/index.tsx
- apps/super-admin/src/pages/PaymentPage/index.tsx
- packages/api/src/queries/index.ts
- packages/api/src/queries/useUserSummary.ts
- packages/api/src/types/adminReservation.ts
- packages/ui/src/components/ShowPreview/ShowPreview.styles.ts
develop -> main 충돌나서 develop에서 브랜치 하나 파서 리베이스함.
> Fix: 슈드민 QA 운영 배포

- packages/api/src/fetcher.ts
- packages/api/src/vite-env.d.ts
> fix: 슈퍼 어드민 환경변수 값 수정

- apps/admin/src/pages/GiftRegisterPage/components/GiftInformation/GiftInformation.styles.ts
- 선물 추가 포스터 이미지 높이 설정
- 공연 초대 메시지 줄바꿈 처리
> fix: 포스터 이미지 높이 설정 및 공연 초대 메시지 줄바꿈 처리

- apps/admin/src/pages/ShowInfoPage/index.tsx
- packages/ui/src/components/ShowPreview/ShowPreviewNotice.styles.ts
- packages/ui/src/components/ShowPreview/index.tsx
- 공연 내용 전체보기 시 스크롤 동작 및 스타일링 문제 수정
- 전체보기에서 다시 돌아왔을 때, 스크롤 위치를 기억하도록 수정
> [운영배포] 공연 내용 전체보기 시 스크롤 동작 및 스타일링 문제 수정

- packages/ui/src/components/ShowPreview/ShowInfoDetail.tsx
- packages/ui/src/components/ShowPreview/ShowPreview.styles.ts
- 티켓 판매 기간 표시
- 공연시간 표기를 뱃지로 수정
> feat: 공연 미리보기 수정사항 반영

- apps/admin/src/components/ShowInfoFormContent/ShowBasicInfoFormContent.tsx
- useDropzone에서 잘못 입력된 accept 입력 수정
> fix: 포스터 업로드가 정상적으로 이루어지지 않는 문제 수정

- apps/admin/src/components/EventPopupContent/EventPopupContent.styles.ts
> fix: 이벤트 팝업 이미지 너비, 높이값 수정

- apps/admin/src/pages/Landing/index.tsx
- packages/api/src/types/popup.ts
- popup view type에 `LANDING` 값 추가
- 홈 팝업과 동일한 팝업을 랜딩페이지에 노출
> feat: 팝업 뷰 타입에 LANDING 값 추가 및 랜딩페이지에서 팝업 노출 추가

- apps/admin/src/components/QuillEditor/QuillEditor.styles.ts
- apps/admin/src/components/QuillEditor/blot.tsx
- apps/admin/src/components/QuillEditor/index.tsx
> feat: 에디터 스타일 적용

- apps/admin/src/pages/ShowInfoPage/index.tsx
This reverts commit c10df9c000040578a3caad0f1b31f2bdf308e5dc.
> 임시 공연 입력 폼 비활성화 로직 해제 복구
